= Спецификация модуля соединяющего асинхронными буферами c приемниками и передатчиками
===========
:Date:      20.12.2017
:Revision:  0.1
:toc:       right
:icons:     font
:source-highlighter: rouge
:table-caption:     Таблица
:listing-caption:   Код
:chapter-label:     Глава
:toc-title:         Оглавление
:version-label:     Версия
:figure-caption:    Рисунок
:imagesdir:         ./../img/

[[main-description]]
== Описание
Модуль используется в проекте приемопередатчика SL канала для чтения управляющих данных из первого асинхронного буфера и записи данных о состоянии приемника / передатчика во второй асинхронный буфер TEST SEQUENCE #7.


[[top-level-description]]
== Описание верхнего уровня

[[input-signals]]
=== Входные сигналы
.Общие сигналы
* clk - системный клок
* rst_n - системный ресет

.Сигналы передатчика
* rd_status_tx - содержимое регистра состояния передатчика
* rd_config_tx - содержимое конфигурационного регистра передатчика
* status_changed_tx - на данный вход поступает импульс от приемника в случае изменения регистра состояния

.Сигналы приемника
* rd_status_rx - содержимое регистра состояния приемника
* rd_config_rx - содержимое конфигурационного регистра приемника
* rd_data_rx - содержимое регистра данных приемника
* data_status_changed_tx - на данный вход поступает импульс от приемника в случае изменения регистра состояния и регистра данных (регистр даннных не может изменится без изменения регистра состояния)

.Сигналы асинхронных буферов
* fifo_read_empty - сигнализирует что входной буфер пуст
* fifo_write_full - сигнализирует что выходной буфер полон
* [33:0] fifo_read_data - шина данных входного буфера

[[output-signals]]
=== Выходные сигналы

.Сигналы передатчика
* wr_config_tx - данные, которые должны быть записаны в конфигурационный регистр
* config_we_tx - сигнал записи в конфигурационный регистр
* wr_data_tx - данные, которые должны быть записаны в регистр для отправляемого сообщения
* data_we_tx - сигнал записывающий данные и начинающий отправку сообщения

.Сигналы приемника
* wr_config_rx - данные, которые должны быть записаны в конфигурационный регистр
* config_we_tx - сигнал для записи в конфигурационный регистр

.Сигналы входного и выходного буферов
* fifo_read_inc - сигнал для чтения из входного буфера
* [33:0] fifo_write_data - шина данных выходного буфера
* fifo_write_inc - сигнал для записи в выходной буфера

[[inout-signals]]
=== Двунаправленные сигналы
Отсутствуют


[[programm-model]]
== Программная модель
.Пользователю для работы доступен регистр:
. Регистр номера канала

Перезаписать содержимое этого регистра можно, поместив сообщение с номером канала и соотвествующим идентификатором. В данном исполнении, регистр имеет один разряд.

.Значения регистра номера канала
* "0"  - модуль сконфигурирован для работы как передатчик
* "1"  - модуль сконифгурирован для работы как приемник

В дальнейшем планируется сделать блок параметризуемым, для возможности подключить N передатчиков и M приемников. Младший бит регистра канала предполагается оставить без изменений, таким образом, каналы на которых приемников будут иметь четный номер, а каналы на передатчиков будут иметь нечетный номер.


[[work-description]]
=== Описание работы модуля
Работа модуля делится на две части - обработка команд поступающих из входного буфера, и чтение данных регистров и потравка их содержиомого через в выходной буфер.
Все данные поступающие из входного буфера и записываемые в выходной снабжаются следующими модификаторами (33 и 34 разряды содержимого сообщения).


.Значения модификаторов для разных регистров
[cols="2*^", width=99%]
|===
|Регистр                   |Значение модификатора
|Конфигурационый           | 2'd0
|Данных                    | 2'd1
|Состояния                 | 2'd2
|Канала                    | 2'd3
|===

.Обработка сообщений из входного буфера
Для обработки сообщений из входного буфера используется машина состояний, работающая по следующему алгоритму:
В зависимости от текущего состояния регистра канала, сообщение читаемое из буфера считается сообщением для соотвествующего канала.
Если выполнены следующие условия, то машина состоний переходит из состояния ожидания в соответвующее состояние обработки сообщения

.Условия перехода
* Буфер не пуст
* Приемник/передатчик не занят (Для сообщений данных и конфигурации)

При этом, при попытке записать данные в передатчик (у него нет входа для регистра данных), а также при сообщении содержащим данные для регистра состояния (запись в регистр состояния запрещена), собщение просто уничтожается.
В случае смены канала, содержимое сообщения записывается в регистр канала,
В случае изменения данных передатчика/приемника на соотвествующие выходы подается сообщение из буфера и write_enable для соответсвующего входа выставляется в "1".

Следующим тактом машина состояний возвращается в состояние ожидания сообщения, единицы на выходах write_enable переключаются в 0.
При смене канала и управлении конфигурационными регистрами генерируются внутренние сигналы "channel_changed" , "rx_config_changed", "tx_config_changed". Их назначение будет описано далее.
.Запись сообщений в выходной буфер
В выходной буфер записываются сообщения следующим образом:

.Серия сообщений записываемая при смене канала (channel_changed == 1)
* текущий канал
* регистр данных текущего канала (только для приемников)
* регистр состояния текущего канала
* конфигурационный регистр текущего канала

.Серия сообщений записываемая при смене регистра состояния модуля, находящегося на текущем канале (data_status_changed_rx == 1 , status_changed_tx)
* регистр данных текущего канала (только для приемников)
* регистр состояния текущего канала
* конфигурационный регистр текущего канала

При config_changed_rx == 1 и config_changed_tx == 1 в асинхронный буфер записывается сообщение с данными текущего регистра

При возникновении коннкурируещего импульса, он будет игнорирован. Возникновение таких ситуаций не предусматривается другими модулями.
