= Спецификация приемопередатчика SL-канала
===========
:Author:    Евгений Власов
:Email:     <evgeniy@npofizika.ru>
:Date:      13.10.2017
:Revision:  0.1
:toc: 		right
:icons: 	font
:source-highlighter: rouge
:table-caption: 	Таблица
:listing-caption: 	Код
:chapter-label: 	Глава
:toc-title: 		Оглавление
:version-label: 	Версия

[[tasks-to-solve]]
== Описание
Данный проект подразумевает реализацию RTL-описания на языке Verilog одноканального приемопередатчика SL-канала. Частота SL - 500кГц.

== Описание SL-канала
SL - канал - последовательный однонаправленный канал обмена данными, разработанный для внутриплатного и межплатного обмена информацией. Обмен данными типа "точка-с-точкой". Канал состоит из двух линий: линии единиц и линии нулей. Пассивный уровень на линиях - единица. В случае передачи данных каждый разряд кодируется отрицательным импульсом на соответствующей линии. Информация передается словами произвольной разрядности младшими разрядами вперед. Предпоследний разряд - четность. Передатчик вычисляет четность таким образом, чтобы количество импульсов на линии единиц с учетом разряда четности было нечетным, а на линии нулей - четным. Приемник контролирует четность индивидуально по каждой линии. Последним импульсом является синхроимпульс, представляющий собой отрицательные импульсы по обоим линиям одновременно. Синхроимпульс означает, что передача закончена. Не допускается перекрытия информационных импульсов во время передачи.

Типичная рабочая частота передатчика, спроектированного в синхронном стиле, составляет от 500кГц до 1МГц. Пауза между информационными битами равна длительности отрицательного импульса.


== Программная модель
Пользователю для работы доступно несколько регистров:
. Конфигурационный
. Статусный
. Полученных данных
. Данных к отправке

=== Конфигурационный регистр

.Назначение разрядов регистра config_r
[cols="16*^", width=99%]
|===
|0     |1       |2    |3    |4    |5    |6    |7    |8    |9    |10    |11    |12    |13    |14    |15
|PCE 5+|BC[5:0] |MODE |IRQM |Res* |Res* |Res* |Res* |Res* |Res* |Res*  |Res*  |Res*  |Res*  |Res*  |Res*
|===


=== Статусный реистр

.Назначение разрядов регистра config_r
[cols="16*^", width=99%]
|===
|0     |1       |2    |3    |4    |5    |6    |7    |8    |9    |10    |11    |12    |13    |14    |15
|PCE 5+|BC[5:0] |MODE |IRQM |Res* |Res* |Res* |Res* |Res* |Res* |Res*  |Res*  |Res*  |Res*  |Res*  |Res*
|===


. config_r[15:0]
	* Конфигурационный регистр
		** 0 - PCE (Parity Check Enable)
		** 1 -

. status_r[15:0]
. buffered_data_r[31:0]
. data_to_send_r[31:0]
